import type {Metadata} from "next";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import {Inter} from "next/font/google";

const inter = Inter({
    variable: "--font-inter",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Jibin | Software Engineer",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={`${inter.variable} antialiased overflow-x-hidden scroll-smooth`}
        >
        <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
